<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { diagnoseRetrieval, getCollectionDocuments, getCollections, getDocumentChunks, reindexCourse, uploadKnowledge } from '../api'
import RetrievedChunkCard from '../components/RetrievedChunkCard.vue'
import { STATUS_LABELS, SUBJECTS, SUBJECT_META } from '../constants'
import { useAppStore } from '../stores/app'
import type { ChunkRecord, CollectionSummary, DiagnosticResult, DocumentRecord, Subject, UploadResult } from '../types'
import { sanitizeQuestionHtml } from '../utils/render'
const app = useAppStore(); const activeTab = ref('manage'); const collections = ref<CollectionSummary[]>([]); const subject = ref<Subject>('数学'); const documents = ref<DocumentRecord[]>([]); const loadingCollections = ref(false); const loadingDocuments = ref(false); const uploadFile = ref<File | null>(null); const uploading = ref(false); const uploadResult = ref<UploadResult | null>(null); const documentKeyword = ref(''); const documentStatus = ref(''); const chunkDialog = ref(false); const chunks = ref<ChunkRecord[]>([]); const selectedDocument = ref<DocumentRecord | null>(null); const loadingChunks = ref(false); const reindexing = ref(false); const diagnosticSubject = ref<Subject>('数学'); const diagnosticQuestion = ref(''); const diagnosticLoading = ref(false); const diagnostic = ref<DiagnosticResult | null>(null)
const currentCollection = computed(() => collections.value.find((item) => item.subject === subject.value)); const filteredDocuments = computed(() => documents.value.filter((item) => (!documentKeyword.value || item.file_name.toLowerCase().includes(documentKeyword.value.toLowerCase())) && (!documentStatus.value || item.status === documentStatus.value)))
async function loadCollections() { loadingCollections.value = true; try { collections.value = await getCollections() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '知识库状态加载失败') } finally { loadingCollections.value = false } }
async function loadDocuments() { loadingDocuments.value = true; try { documents.value = await getCollectionDocuments(SUBJECT_META[subject.value].collection) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '文档列表加载失败') } finally { loadingDocuments.value = false } }
function chooseUpload(event: Event) { const target = event.target as HTMLInputElement; const selected = target.files?.[0] || null; if (!selected) return; const suffix = selected.name.split('.').pop()?.toLowerCase(); if (!['pdf', 'docx', 'txt', 'md', 'markdown'].includes(suffix || '')) { ElMessage.error('资料仅支持 PDF、DOCX、TXT 或 Markdown'); target.value = ''; return } if (selected.size > 50 * 1024 * 1024) { ElMessage.error('文件不能超过 50MB'); target.value = ''; return } uploadFile.value = selected }
async function submitUpload() { if (!uploadFile.value) return ElMessage.warning('请先选择资料文件'); uploading.value = true; uploadResult.value = null; try { uploadResult.value = await uploadKnowledge(subject.value, SUBJECT_META[subject.value].collection, uploadFile.value); ElMessage.success(`资料已切分为 ${uploadResult.value.chunks} 个知识片段`); uploadFile.value = null; await Promise.all([loadCollections(), loadDocuments()]) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '资料上传失败') } finally { uploading.value = false } }
async function showChunks(document: DocumentRecord) { selectedDocument.value = document; chunkDialog.value = true; loadingChunks.value = true; try { chunks.value = await getDocumentChunks(document.id) } catch (error) { ElMessage.error(error instanceof Error ? error.message : 'Chunk 加载失败') } finally { loadingChunks.value = false } }
async function reindex() { const courseId = currentCollection.value?.course_id; if (!courseId) return ElMessage.warning('该学科还没有可重建的知识库'); try { await ElMessageBox.confirm('重新索引会重新处理该学科的全部文档，过程可能持续数分钟。确定继续吗？', '重新索引', { type: 'warning' }); reindexing.value = true; const result = await reindexCourse(courseId); ElMessage.success(`重新索引完成，共写入 ${result.indexed_chunks || 0} 个知识片段`); await Promise.all([loadCollections(), loadDocuments()]) } catch (error) { if (error instanceof Error && error.message) ElMessage.error(error.message) } finally { reindexing.value = false } }
async function runDiagnostic() { const text = diagnosticQuestion.value.trim(); if (!text) return ElMessage.warning('请输入用于测试检索的问题'); diagnosticLoading.value = true; try { diagnostic.value = await diagnoseRetrieval(SUBJECT_META[diagnosticSubject.value].collection, text); ElMessage.success(`检索完成，返回 ${diagnostic.value.retrieved_chunks.length} 个结果`) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '检索诊断失败') } finally { diagnosticLoading.value = false } }
async function copyDiagnostic() { if (!diagnostic.value) return; await navigator.clipboard.writeText(JSON.stringify({ subject: diagnosticSubject.value, question: diagnosticQuestion.value, ...diagnostic.value }, null, 2)); ElMessage.success('检索结果 JSON 已复制') }
async function copyChunkId(chunk: ChunkRecord) { await navigator.clipboard.writeText(chunk.chunk_id); ElMessage.success('Chunk ID 已复制') }
async function copyChunkText(chunk: ChunkRecord) { await navigator.clipboard.writeText(chunk.content); ElMessage.success('Chunk 文本已复制') }
watch(subject, loadDocuments); onMounted(async () => { await loadCollections(); await loadDocuments() })
</script>
<template><section class="standard-page knowledge-page"><header class="page-header"><div><span class="eyebrow">教师知识工作台</span><h1>知识库管理</h1><p>管理课程资料、检查切块质量，并用真实问题验证向量检索效果。</p></div></header><el-tabs v-model="activeTab" class="workspace-tabs">
<el-tab-pane label="资料与索引" name="manage"><div class="collection-grid" v-loading="loadingCollections"><button v-for="item in collections" :key="item.name" type="button" class="collection-card" :class="{ active: subject === item.subject }" @click="subject = item.subject"><span class="collection-icon" :style="{ background: SUBJECT_META[item.subject].color }">{{ SUBJECT_META[item.subject].short }}</span><div class="collection-title"><strong>{{ item.subject }}知识库</strong><small>{{ SUBJECT_META[item.subject].description }}</small></div><div class="collection-metrics"><span><b>{{ item.document_count }}</b> 份资料</span><span><b>{{ item.chunk_count }}</b> 个片段</span></div><div class="collection-status"><span class="success">{{ item.indexed_count }} 已完成</span><span class="pending">{{ item.pending_count }} 处理中</span><span v-if="item.failed_count" class="failed">{{ item.failed_count }} 失败</span></div></button></div>
<div class="knowledge-layout"><article class="content-panel upload-panel"><div class="panel-heading"><div><span class="eyebrow">导入 {{ subject }}资料</span><h3>扩充学科知识库</h3></div><span class="collection-code">{{ SUBJECT_META[subject].collection }}</span></div><label class="knowledge-dropzone" :class="{ selected: uploadFile }"><input type="file" accept=".pdf,.docx,.txt,.md,.markdown" @change="chooseUpload"><span>{{ uploadFile ? '✓' : '↑' }}</span><strong>{{ uploadFile?.name || '点击选择课程资料' }}</strong><small>{{ uploadFile ? `${(uploadFile.size / 1024 / 1024).toFixed(2)} MB` : 'PDF、DOCX、TXT、Markdown，最大 50MB' }}</small></label><el-button type="primary" size="large" :loading="uploading" :disabled="!uploadFile" class="full-button" @click="submitUpload">上传并建立索引</el-button><el-alert v-if="uploadResult" :title="`${uploadResult.file_name}：${uploadResult.status === 'indexed' ? '索引完成' : uploadResult.status}，生成 ${uploadResult.chunks} 个片段`" :type="uploadResult.status === 'indexed' ? 'success' : 'warning'" show-icon :closable="false" /></article>
<article class="content-panel collection-summary-panel"><div class="panel-heading"><div><span class="eyebrow">当前状态</span><h3>{{ subject }}知识库</h3></div><el-button :loading="reindexing" @click="reindex">重新索引</el-button></div><dl class="summary-list"><div><dt>文档总数</dt><dd>{{ currentCollection?.document_count || 0 }}</dd></div><div><dt>知识片段</dt><dd>{{ currentCollection?.chunk_count || 0 }}</dd></div><div><dt>索引成功</dt><dd>{{ currentCollection?.indexed_count || 0 }}</dd></div><div><dt>索引失败</dt><dd :class="{ danger: currentCollection?.failed_count }">{{ currentCollection?.failed_count || 0 }}</dd></div></dl><p class="muted-note">浏览器不会直接连接向量数据库，所有上传、检索和重建操作均由 FastAPI 后端统一处理。</p></article></div>
<article class="content-panel document-panel"><div class="panel-heading"><div><span class="eyebrow">已导入资料</span><h3>文档与切块</h3></div><div class="table-filters"><el-input v-model="documentKeyword" placeholder="搜索文件名" clearable /><el-select v-model="documentStatus" placeholder="全部状态" clearable><el-option label="已完成" value="indexed" /><el-option label="处理中" value="pending" /><el-option label="失败" value="failed" /></el-select></div></div><el-table :data="filteredDocuments" v-loading="loadingDocuments" empty-text="当前学科还没有导入资料"><el-table-column prop="file_name" label="文件名" min-width="260" show-overflow-tooltip /><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.status === 'indexed' ? 'success' : scope.row.status === 'failed' ? 'danger' : 'warning'">{{ STATUS_LABELS[scope.row.status] || scope.row.status }}</el-tag></template></el-table-column><el-table-column prop="chunk_count" label="Chunk" width="90" /><el-table-column label="导入时间" width="180"><template #default="scope">{{ new Date(scope.row.created_at).toLocaleString('zh-CN') }}</template></el-table-column><el-table-column label="操作" width="120"><template #default="scope"><el-button link type="primary" @click="showChunks(scope.row)">查看切块</el-button></template></el-table-column></el-table></article></el-tab-pane>
<el-tab-pane label="检索诊断" name="diagnostic"><div class="diagnostic-intro"><div><span class="eyebrow">向量库优化工具</span><h2>用真实问题检查 Top K 结果</h2><p>这里只执行路由和向量检索，不调用大模型生成答案，也不会写入学生会话历史。</p></div><span class="safe-badge">只读诊断</span></div><article class="content-panel diagnostic-form"><div class="form-field"><label>测试学科</label><div class="subject-switch compact"><button v-for="item in SUBJECTS" :key="item" type="button" :class="{ active: diagnosticSubject === item }" @click="diagnosticSubject = item"><span :style="{ background: SUBJECT_META[item].color }">{{ SUBJECT_META[item].short }}</span>{{ item }}</button></div></div><div class="diagnostic-input"><el-input v-model="diagnosticQuestion" type="textarea" :rows="3" placeholder="输入一个学生可能提出的真实问题，观察向量库返回了哪些片段" @keydown.ctrl.enter="runDiagnostic" /><el-button type="primary" size="large" :loading="diagnosticLoading" @click="runDiagnostic">开始检索</el-button></div></article>
<div v-if="diagnostic" class="diagnostic-result"><div class="result-banner compact-banner"><div><span class="eyebrow">检索结果</span><h2>返回 {{ diagnostic.retrieved_chunks.length }} 个匹配片段</h2><p>路由：{{ diagnostic.route }} · 置信度：{{ diagnostic.confidence }}</p></div><el-button @click="copyDiagnostic">复制 JSON</el-button></div><div class="source-grid"><RetrievedChunkCard v-for="(chunk, index) in diagnostic.retrieved_chunks" :key="String(chunk.metadata?.chunk_id || index)" :chunk="chunk" :index="index" diagnostic @select="app.openSource" /></div><el-empty v-if="!diagnostic.retrieved_chunks.length" description="没有达到当前检索阈值的知识片段" /></div><div v-else class="feature-placeholder small"><div class="placeholder-graphic">检</div><h2>尚未执行检索</h2><p>选择学科并输入测试问题，相似度、来源、题号和 OCR 文本会显示在这里。</p></div></el-tab-pane></el-tabs>
<el-drawer v-model="chunkDialog" size="min(720px, 94vw)" title="文档切块详情" append-to-body><div class="chunk-drawer-heading"><h3>{{ selectedDocument?.file_name }}</h3><p>共 {{ chunks.length }} 个 Chunk，点击展开查看完整内容。</p></div><el-skeleton v-if="loadingChunks" :rows="8" animated /><el-collapse v-else><el-collapse-item v-for="(chunk, index) in chunks" :key="chunk.chunk_id" :name="chunk.chunk_id"><template #title><span class="chunk-collapse-title"><b>#{{ index + 1 }}</b><span>{{ chunk.section_title || chunk.metadata.question_type || '未命名片段' }}</span><code>{{ chunk.chunk_id }}</code></span></template><div class="chunk-full"><div v-if="chunk.metadata.display_html" class="question-detail" v-html="sanitizeQuestionHtml(String(chunk.metadata.display_html))" /><p v-else>{{ chunk.content }}</p><dl class="source-metadata"><div><dt>页码</dt><dd>{{ chunk.page || '-' }}</dd></div><div><dt>题号</dt><dd>{{ chunk.metadata.question_no || '-' }}</dd></div><div><dt>题型</dt><dd>{{ chunk.metadata.question_type || '-' }}</dd></div></dl><el-button size="small" @click="copyChunkId(chunk)">复制 Chunk ID</el-button><el-button size="small" @click="copyChunkText(chunk)">复制文本</el-button></div></el-collapse-item></el-collapse></el-drawer></section></template>
