<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { analyzePaper } from '../api'
import MarkdownContent from '../components/MarkdownContent.vue'
import RetrievedChunkCard from '../components/RetrievedChunkCard.vue'
import { SUBJECTS, SUBJECT_META } from '../constants'
import { useAppStore } from '../stores/app'
import type { PaperAnalysisResult, PaperQuestion, Subject } from '../types'
import { sanitizeQuestionHtml } from '../utils/render'
const CACHE_KEY = 'education_last_paper_analysis'; const app = useAppStore(); const subject = ref<Subject>('数学'); const focus = ref(''); const file = ref<File | null>(null); const loading = ref(false); const elapsed = ref(0); const activeTab = ref('overview'); const keyword = ref(''); const typeFilter = ref(''); const knowledgeFilter = ref(''); const imagePreview = ref(''); let timer = 0
function loadCached(): PaperAnalysisResult | null { try { return JSON.parse(sessionStorage.getItem(CACHE_KEY) || 'null') as PaperAnalysisResult | null } catch { return null } }
const result = ref<PaperAnalysisResult | null>(loadCached())
const typeCounts = computed(() => { const counts: Record<string, number> = {}; result.value?.questions.forEach((item) => { const key = item.question_type || '未知题型'; counts[key] = (counts[key] || 0) + 1 }); return counts })
const knowledgeCounts = computed(() => { const counts: Record<string, number> = {}; result.value?.questions.forEach((item) => item.knowledge_points.forEach((point) => { counts[point] = (counts[point] || 0) + 1 })); return Object.entries(counts).sort((a, b) => b[1] - a[1]) })
const qualityIssueCount = computed(() => result.value?.questions.filter((item) => item.quality_flags.length).length || 0); const questionTypes = computed(() => Object.keys(typeCounts.value)); const knowledgeOptions = computed(() => knowledgeCounts.value.map(([name]) => name))
const filteredQuestions = computed(() => (result.value?.questions || []).filter((item) => { const haystack = `${item.question_no} ${item.stem} ${item.analysis}`.toLowerCase(); return (!keyword.value || haystack.includes(keyword.value.toLowerCase())) && (!typeFilter.value || item.question_type === typeFilter.value) && (!knowledgeFilter.value || item.knowledge_points.includes(knowledgeFilter.value)) }))
function chooseFile(event: Event) { const target = event.target as HTMLInputElement; const selected = target.files?.[0] || null; if (!selected) return; const suffix = selected.name.split('.').pop()?.toLowerCase(); if (!['pdf', 'docx'].includes(suffix || '')) { ElMessage.error('试卷仅支持 PDF 或 DOCX 文件'); target.value = ''; return } if (selected.size > 50 * 1024 * 1024) { ElMessage.error('文件不能超过 50MB'); target.value = ''; return } file.value = selected }
async function submit() { if (!file.value) return ElMessage.warning('请先选择试卷文件'); loading.value = true; elapsed.value = 0; timer = window.setInterval(() => elapsed.value += 1, 1000); try { result.value = await analyzePaper(subject.value, focus.value, file.value); try { sessionStorage.setItem(CACHE_KEY, JSON.stringify(result.value)) } catch { /* keep in memory */ } activeTab.value = 'overview'; ElMessage.success(`已识别 ${result.value.questions.length} 道题目`) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '试卷分析失败') } finally { loading.value = false; window.clearInterval(timer) } }
async function copyReport() { if (!result.value) return; await navigator.clipboard.writeText(result.value.report_markdown); ElMessage.success('分析报告已复制') }
function questionHtml(question: PaperQuestion) { return question.display_html ? sanitizeQuestionHtml(question.display_html) : '' }
onBeforeUnmount(() => window.clearInterval(timer))
</script>
<template><section class="standard-page papers-page"><header class="page-header"><div><span class="eyebrow">教师分析工作台</span><h1>试卷智能分析</h1><p>上传试卷后，系统会完成题目切分、知识点提取和可追溯报告生成。</p></div></header>
<div class="paper-upload-panel"><div class="form-field"><label>试卷学科</label><div class="subject-switch compact"><button v-for="item in SUBJECTS" :key="item" type="button" :class="{ active: subject === item }" @click="subject = item"><span :style="{ background: SUBJECT_META[item].color }">{{ SUBJECT_META[item].short }}</span>{{ item }}</button></div></div><div class="form-field grow"><label>重点分析要求 <small>选填</small></label><el-input v-model="focus" placeholder="例如：重点分析函数与导数题型，并给出复习建议" clearable /></div><label class="file-picker" :class="{ selected: file }"><input type="file" accept=".pdf,.docx" @change="chooseFile"><span class="file-icon">{{ file ? '✓' : '↑' }}</span><span><strong>{{ file?.name || '选择试卷文件' }}</strong><small>{{ file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : '支持 PDF、DOCX，最大 50MB' }}</small></span></label><el-button type="primary" size="large" :loading="loading" :disabled="!file" @click="submit">开始分析</el-button><div v-if="loading" class="processing-note"><span class="pulse" />正在上传、解析并建立索引，已用时 {{ elapsed }} 秒。大文件可能需要数分钟，请勿关闭页面。</div></div>
<div v-if="!result" class="feature-placeholder"><div class="placeholder-graphic">卷</div><h2>从一份试卷开始</h2><p>分析完成后，这里会展示题型统计、知识点分布、逐题解析与检索依据。</p><div class="feature-points"><span>题型统计</span><span>知识点提取</span><span>原题溯源</span><span>复习建议</span></div></div>
<div v-else class="analysis-result"><div class="result-banner"><div><span class="eyebrow">分析完成</span><h2>{{ result.file_name }}</h2><p>{{ result.subject }} · {{ result.agent }} · {{ result.chunks }} 个知识片段</p></div><el-tag :type="result.status === 'indexed' ? 'success' : 'warning'" size="large">{{ result.status === 'indexed' ? '索引完成' : result.status }}</el-tag></div><el-alert v-if="result.error_message" :title="result.error_message" type="warning" show-icon :closable="false" />
<el-tabs v-model="activeTab" class="result-tabs"><el-tab-pane label="分析概览" name="overview"><div class="metric-grid"><div class="metric-card"><span>识别题目</span><strong>{{ result.questions.length }}</strong><small>道</small></div><div class="metric-card"><span>题型种类</span><strong>{{ Object.keys(typeCounts).length }}</strong><small>类</small></div><div class="metric-card"><span>知识点</span><strong>{{ knowledgeCounts.length }}</strong><small>个</small></div><div class="metric-card" :class="{ warning: qualityIssueCount }"><span>需核对题目</span><strong>{{ qualityIssueCount }}</strong><small>道</small></div></div><div class="overview-grid"><article class="content-panel"><h3>题型统计</h3><div v-for="(count, name) in typeCounts" :key="name" class="stat-row"><span>{{ name }}</span><div><i :style="{ width: `${Math.max(8, count / result.questions.length * 100)}%` }" /></div><strong>{{ count }}</strong></div></article><article class="content-panel"><h3>高频知识点</h3><div class="knowledge-cloud"><span v-for="([name, count]) in knowledgeCounts" :key="name">{{ name }} <b>{{ count }}</b></span><p v-if="!knowledgeCounts.length">暂未提取到稳定知识点</p></div></article></div><el-alert v-if="qualityIssueCount" :title="`${qualityIssueCount} 道题存在答案、解析或题干字段不完整，建议结合原题图片核对。`" type="warning" show-icon :closable="false" /></el-tab-pane>
<el-tab-pane :label="`题目列表 ${result.questions.length}`" name="questions"><div class="filter-bar"><el-input v-model="keyword" placeholder="搜索题号或题干" clearable /><el-select v-model="typeFilter" placeholder="全部题型" clearable><el-option v-for="item in questionTypes" :key="item" :label="item" :value="item" /></el-select><el-select v-model="knowledgeFilter" placeholder="全部知识点" clearable><el-option v-for="item in knowledgeOptions" :key="item" :label="item" :value="item" /></el-select><span>共 {{ filteredQuestions.length }} 题</span></div><div class="question-list"><article v-for="questionItem in filteredQuestions" :key="questionItem.chunk_id" class="question-card"><header><div><span class="question-number">第 {{ questionItem.question_no || '-' }} 题</span><el-tag effect="plain">{{ questionItem.question_type || '未知题型' }}</el-tag></div><button v-if="questionItem.question_image_url" type="button" class="text-button" @click="imagePreview = questionItem.question_image_url">查看原题</button></header><div v-if="questionHtml(questionItem)" class="question-detail" v-html="questionHtml(questionItem)" /><p v-else class="question-stem">{{ questionItem.stem || '题干未识别' }}</p><ul v-if="questionItem.options.length" class="question-options"><li v-for="option in questionItem.options" :key="option">{{ option }}</li></ul><div class="answer-analysis"><div><strong>参考答案</strong><p>{{ questionItem.answer || '未识别' }}</p></div><div><strong>解析</strong><p>{{ questionItem.analysis || '未识别，建议结合原题核对' }}</p></div></div><footer><span v-for="point in questionItem.knowledge_points" :key="point">{{ point }}</span><el-tag v-for="flag in questionItem.quality_flags" :key="flag" type="warning" size="small">{{ flag }}</el-tag></footer></article></div></el-tab-pane>
<el-tab-pane label="分析报告" name="report"><article class="report-panel"><div class="panel-heading"><div><span class="eyebrow">Markdown 报告</span><h3>试卷分析与复习建议</h3></div><el-button @click="copyReport">复制报告</el-button></div><MarkdownContent :content="result.report_markdown" /></article></el-tab-pane><el-tab-pane :label="`检索依据 ${result.retrieved_chunks.length}`" name="sources"><div class="source-grid"><RetrievedChunkCard v-for="(chunk, index) in result.retrieved_chunks" :key="String(chunk.metadata?.chunk_id || index)" :chunk="chunk" :index="index" diagnostic @select="app.openSource" /></div><el-empty v-if="!result.retrieved_chunks.length" description="本次分析没有额外检索到匹配资料" /></el-tab-pane></el-tabs></div>
<el-dialog :model-value="!!imagePreview" title="原题图片" width="min(920px, 94vw)" destroy-on-close @close="imagePreview = ''"><el-image :src="imagePreview" :preview-src-list="[imagePreview]" fit="contain" class="paper-image" /></el-dialog></section></template>
